before_install:
  - sudo apt-get update
  - sudo apt-get install -y libcups2 cups libcups2-dev cups-bsd cups-client libcupsimage2-dev libdbus-1-dev build-essential ghostscript openssl libjpeg-turbo8-dev libsnmp-dev libtool libusb-1.0-0-dev wget python-imaging policykit-1 policykit-1-gnome python-qt4 python-qt4-dbus python-dbus python-gobject python-dev python-notify python python-reportlab libsane libsane-dev sane-utils xsane

compiler:
  - gcc

jobs: 
  - stage: configure
    name: "Configure, initial make, make dist package, make deb"
    script: ./configure --enable-dependency-tracking --enable-apparmor_build --with-gnu-ld && make && make dist && make deb
