before_install:
- sudo apt-get update
- sudo apt-get install -y libcups2 cups libcups2-dev cups-bsd cups-client libcupsimage2-dev
  libdbus-1-dev ghostscript openssl libjpeg-turbo8-dev libsnmp-dev libtool libusb-1.0-0-dev
  wget python-imaging policykit-1 policykit-1-gnome python-qt4 python-qt4-dbus python-dbus
  python-gobject python-dev python-notify python python-reportlab libsane libsane-dev
  sane-utils xsane epm

before_deploy:
  - git config --local user.name "azfirefighter"
  - git config --local user.email "jake@lltodd.family"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

compiler:
- gcc

jobs:
- stage: Dist
  name: Configure, initial make, make dist package
  script: "./configure --enable-static --enable-dependency-tracking --enable-apparmor_build --with-gnu-ld
    && make && sudo make dist"
  deploy:
    provider: releases
    file: hplip-3.19.11.tar.gz
    skip_cleanup: true
    api_key:
      secure: 88tr1LrFNy0heDGhPQ7Q6lZGj6AI2uDOR8BFnol2h2Qr+RRmHUMeGugfe5bpakm0SASpAGPQieSmPS1cb/xpWICAN87Ljr1vWv/CY2pJnfvGIr7/cyVLVStQgz$
- stage: Deb
  name: Make deb file
  script:  "./configure --enable-static --enable-dependency-tracking --enable-apparmor_build --with-gnu-dl && make && sudo make dist && sudo make deb
  deploy:
    provider: releases
    file: hplipfull-3.19.11-linux-4.15-x86_64.deb
    skip_cleanup: true
    api_key:
      secure: 88tr1LrFNy0heDGhPQ7Q6lZGj6AI2uDOR8BFnol2h2Qr+RRmHUMeGugfe5bpakm0SASpAGPQieSmPS1cb/xpWICAN87Ljr1vWv/CY2pJnfvGIr7/cyVLVStQ$
